name: musicfox
description: A sample command-line application.
version: 1.0.0
homepage: https://danlanhai.gitee.io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mp3_player: ^0.1.2
  colorful_cmd: ^1.3.2
  console: ^3.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
